#!/usr/bin/env swift

import Foundation

struct CatalogFile: Decodable {
    let geometries: [GeometryDefinition]
    let heuristics: [HeuristicDefinition]
    let modelGroups: [ModelGroup]
}

struct GeometryDefinition: Decodable {
    let name: String
    let style: String
    let width: Double
    let height: Double
    let topInset: Double
}

struct HeuristicDefinition: Decodable {
    let screenWidth: Int
    let safeAreaTop: Int
    let geometry: String
}

struct ModelGroup: Decodable {
    let comment: String
    let geometry: String
    let identifiers: [ModelIdentifier]
}

struct ModelIdentifier: Decodable {
    let id: String
    let comment: String?
}

let fileManager = FileManager.default
let scriptURL = URL(fileURLWithPath: CommandLine.arguments[0]).standardizedFileURL
let repoRootURL = scriptURL.deletingLastPathComponent()
let inputURL = repoRootURL.appendingPathComponent("top_cutout_catalog.json")
let outputURL = repoRootURL.appendingPathComponent("Sources/TopCutout/TopCutoutCatalog.generated.swift")

func fail(_ message: String) -> Never {
    FileHandle.standardError.write(Data((message + "\n").utf8))
    exit(1)
}

func swiftNumber(_ value: Double) -> String {
    let rounded = value.rounded()
    if abs(value - rounded) < 0.000_001 {
        return String(Int(rounded))
    }

    return String(value)
}

let decoder = JSONDecoder()
decoder.keyDecodingStrategy = .useDefaultKeys

let data: Data
do {
    data = try Data(contentsOf: inputURL)
} catch {
    fail("Failed to read catalog JSON at \(inputURL.path): \(error)")
}

let catalog: CatalogFile
do {
    catalog = try decoder.decode(CatalogFile.self, from: data)
} catch {
    fail("Failed to decode catalog JSON: \(error)")
}

let geometryNames = Set(catalog.geometries.map(\.name))
for heuristic in catalog.heuristics where !geometryNames.contains(heuristic.geometry) {
    fail("Unknown heuristic geometry reference: \(heuristic.geometry)")
}

for group in catalog.modelGroups where !geometryNames.contains(group.geometry) {
    fail("Unknown model group geometry reference: \(group.geometry)")
}

let duplicateGeometryNames = Dictionary(grouping: catalog.geometries, by: \.name).filter { $0.value.count > 1 }.keys
if let duplicate = duplicateGeometryNames.sorted().first {
    fail("Duplicate geometry name: \(duplicate)")
}

let allIdentifiers = catalog.modelGroups.flatMap(\.identifiers).map(\.id)
let duplicateIdentifiers = Dictionary(grouping: allIdentifiers, by: { $0 }).filter { $0.value.count > 1 }.keys
if let duplicate = duplicateIdentifiers.sorted().first {
    fail("Duplicate model identifier: \(duplicate)")
}

var lines: [String] = []

lines.append("import UIKit")
lines.append("")
lines.append("// This file is generated by generate_top_cutout_catalog.swift.")
lines.append("// Do not edit it directly. Update top_cutout_catalog.json and regenerate instead.")
lines.append("")
lines.append("extension IPhoneTopCutoutCatalog {")
lines.append("    static func generatedHeuristicGeometry(")
lines.append("        screenSize: CGSize,")
lines.append("        safeAreaTop: CGFloat")
lines.append("    ) -> TopCutoutGeometry? {")
lines.append("        let width = Int(screenSize.width.rounded())")
lines.append("        let top = Int(safeAreaTop.rounded())")
lines.append("")
lines.append("        switch (width, top) {")

for heuristic in catalog.heuristics {
    lines.append("        case (\(heuristic.screenWidth), \(heuristic.safeAreaTop)):")
    lines.append("            return \(heuristic.geometry)")
}

lines.append("        default:")
lines.append("            return nil")
lines.append("        }")
lines.append("    }")
lines.append("")

for geometry in catalog.geometries {
    lines.append("    static let \(geometry.name) = TopCutoutGeometry(")
    lines.append("        style: .\(geometry.style),")
    lines.append("        size: CGSize(width: \(swiftNumber(geometry.width)), height: \(swiftNumber(geometry.height))),")
    lines.append("        topInset: \(swiftNumber(geometry.topInset))")
    lines.append("    )")
    lines.append("")
}

lines.append("    static let generatedMap: [String: TopCutoutGeometry] = {")
lines.append("        var result: [String: TopCutoutGeometry] = [:]")
lines.append("")
lines.append("        func assign(_ ids: [String], _ geometry: TopCutoutGeometry) {")
lines.append("            ids.forEach { result[$0] = geometry }")
lines.append("        }")
lines.append("")

for group in catalog.modelGroups {
    lines.append("        // \(group.comment)")
    lines.append("        assign([")

    for identifier in group.identifiers {
        if let comment = identifier.comment {
            lines.append("            \"\(identifier.id)\", // \(comment)")
        } else {
            lines.append("            \"\(identifier.id)\"")
        }
    }

    lines.append("        ], \(group.geometry))")
    lines.append("")
}

lines.append("        return result")
lines.append("    }()")
lines.append("}")
lines.append("")

let output = lines.joined(separator: "\n")

do {
    if !fileManager.fileExists(atPath: outputURL.deletingLastPathComponent().path) {
        try fileManager.createDirectory(at: outputURL.deletingLastPathComponent(), withIntermediateDirectories: true)
    }

    try output.write(to: outputURL, atomically: true, encoding: .utf8)
} catch {
    fail("Failed to write generated Swift file at \(outputURL.path): \(error)")
}
