import UIKit

// Generated by inspect_simulator_topcutouts.py
extension IPhoneDevice {
    public var screenInfo: IPhoneScreenInfo {
        switch self {
        case .iPhone6s:
            return IPhoneScreenInfo(
                cornerRadiusPoints: nil,
                dpi: 326,
                pixels: CGSize(
                    width: 750,
                    height: 1334
                ),
                points: CGSize(
                    width: 375,
                    height: 667
                ),
                scale: 2,
                topFeature: IPhoneTopFeatureInfo(
                    kind: .none,
                    geometryAvailable: false,
                    curveAvailable: false,
                    size: nil,
                    paddingTop: nil
                )
            )
        case .iPhone6sPlus:
            return IPhoneScreenInfo(
                cornerRadiusPoints: 0,
                dpi: 461,
                pixels: CGSize(
                    width: 1242,
                    height: 2208
                ),
                points: CGSize(
                    width: 414,
                    height: 736
                ),
                scale: 3,
                topFeature: IPhoneTopFeatureInfo(
                    kind: .none,
                    geometryAvailable: false,
                    curveAvailable: false,
                    size: nil,
                    paddingTop: nil
                )
            )
        case .iPhoneSE1stGeneration:
            return IPhoneScreenInfo(
                cornerRadiusPoints: nil,
                dpi: 326,
                pixels: CGSize(
                    width: 640,
                    height: 1136
                ),
                points: CGSize(
                    width: 320,
                    height: 568
                ),
                scale: 2,
                topFeature: IPhoneTopFeatureInfo(
                    kind: .none,
                    geometryAvailable: false,
                    curveAvailable: false,
                    size: nil,
                    paddingTop: nil
                )
            )
        case .iPhone7:
            return IPhoneScreenInfo(
                cornerRadiusPoints: nil,
                dpi: 326,
                pixels: CGSize(
                    width: 750,
                    height: 1334
                ),
                points: CGSize(
                    width: 375,
                    height: 667
                ),
                scale: 2,
                topFeature: IPhoneTopFeatureInfo(
                    kind: .none,
                    geometryAvailable: false,
                    curveAvailable: false,
                    size: nil,
                    paddingTop: nil
                )
            )
        case .iPhone7Plus:
            return IPhoneScreenInfo(
                cornerRadiusPoints: 0,
                dpi: 461,
                pixels: CGSize(
                    width: 1242,
                    height: 2208
                ),
                points: CGSize(
                    width: 414,
                    height: 736
                ),
                scale: 3,
                topFeature: IPhoneTopFeatureInfo(
                    kind: .none,
                    geometryAvailable: false,
                    curveAvailable: false,
                    size: nil,
                    paddingTop: nil
                )
            )
        case .iPhone8:
            return IPhoneScreenInfo(
                cornerRadiusPoints: 0,
                dpi: 326,
                pixels: CGSize(
                    width: 750,
                    height: 1334
                ),
                points: CGSize(
                    width: 375,
                    height: 667
                ),
                scale: 2,
                topFeature: IPhoneTopFeatureInfo(
                    kind: .none,
                    geometryAvailable: false,
                    curveAvailable: false,
                    size: nil,
                    paddingTop: nil
                )
            )
        case .iPhone8Plus:
            return IPhoneScreenInfo(
                cornerRadiusPoints: 0,
                dpi: 461,
                pixels: CGSize(
                    width: 1242,
                    height: 2208
                ),
                points: CGSize(
                    width: 414,
                    height: 736
                ),
                scale: 3,
                topFeature: IPhoneTopFeatureInfo(
                    kind: .none,
                    geometryAvailable: false,
                    curveAvailable: false,
                    size: nil,
                    paddingTop: nil
                )
            )
        case .iPhoneX:
            return IPhoneScreenInfo(
                cornerRadiusPoints: 39,
                dpi: 458,
                pixels: CGSize(
                    width: 1125,
                    height: 2436
                ),
                points: CGSize(
                    width: 375,
                    height: 812
                ),
                scale: 3,
                topFeature: IPhoneTopFeatureInfo(
                    kind: .notch,
                    geometryAvailable: true,
                    curveAvailable: true,
                    size: CGSize(
                        width: 223,
                        height: 30
                    ),
                    paddingTop: 0
                )
            )
        case .iPhoneXs:
            return IPhoneScreenInfo(
                cornerRadiusPoints: 39,
                dpi: 458,
                pixels: CGSize(
                    width: 1125,
                    height: 2436
                ),
                points: CGSize(
                    width: 375,
                    height: 812
                ),
                scale: 3,
                topFeature: IPhoneTopFeatureInfo(
                    kind: .notch,
                    geometryAvailable: true,
                    curveAvailable: true,
                    size: CGSize(
                        width: 223,
                        height: 30
                    ),
                    paddingTop: 0
                )
            )
        case .iPhoneXsMax:
            return IPhoneScreenInfo(
                cornerRadiusPoints: 39,
                dpi: 458,
                pixels: CGSize(
                    width: 1242,
                    height: 2688
                ),
                points: CGSize(
                    width: 414,
                    height: 896
                ),
                scale: 3,
                topFeature: IPhoneTopFeatureInfo(
                    kind: .notch,
                    geometryAvailable: true,
                    curveAvailable: true,
                    size: CGSize(
                        width: 223,
                        height: 30
                    ),
                    paddingTop: 0
                )
            )
        case .iPhoneXR:
            return IPhoneScreenInfo(
                cornerRadiusPoints: 41.5,
                dpi: 326,
                pixels: CGSize(
                    width: 828,
                    height: 1792
                ),
                points: CGSize(
                    width: 414,
                    height: 896
                ),
                scale: 2,
                topFeature: IPhoneTopFeatureInfo(
                    kind: .notch,
                    geometryAvailable: true,
                    curveAvailable: true,
                    size: CGSize(
                        width: 245,
                        height: 33
                    ),
                    paddingTop: 0
                )
            )
        case .iPhone11:
            return IPhoneScreenInfo(
                cornerRadiusPoints: 41.5,
                dpi: 326,
                pixels: CGSize(
                    width: 828,
                    height: 1792
                ),
                points: CGSize(
                    width: 414,
                    height: 896
                ),
                scale: 2,
                topFeature: IPhoneTopFeatureInfo(
                    kind: .notch,
                    geometryAvailable: true,
                    curveAvailable: true,
                    size: CGSize(
                        width: 245,
                        height: 33
                    ),
                    paddingTop: 0
                )
            )
        case .iPhone11Pro:
            return IPhoneScreenInfo(
                cornerRadiusPoints: 39,
                dpi: 458,
                pixels: CGSize(
                    width: 1125,
                    height: 2436
                ),
                points: CGSize(
                    width: 375,
                    height: 812
                ),
                scale: 3,
                topFeature: IPhoneTopFeatureInfo(
                    kind: .notch,
                    geometryAvailable: true,
                    curveAvailable: true,
                    size: CGSize(
                        width: 223,
                        height: 30
                    ),
                    paddingTop: 0
                )
            )
        case .iPhone11ProMax:
            return IPhoneScreenInfo(
                cornerRadiusPoints: 39,
                dpi: 458,
                pixels: CGSize(
                    width: 1242,
                    height: 2688
                ),
                points: CGSize(
                    width: 414,
                    height: 896
                ),
                scale: 3,
                topFeature: IPhoneTopFeatureInfo(
                    kind: .notch,
                    geometryAvailable: true,
                    curveAvailable: true,
                    size: CGSize(
                        width: 223,
                        height: 30
                    ),
                    paddingTop: 0
                )
            )
        case .iPhoneSE2ndGeneration:
            return IPhoneScreenInfo(
                cornerRadiusPoints: 0,
                dpi: 326,
                pixels: CGSize(
                    width: 750,
                    height: 1334
                ),
                points: CGSize(
                    width: 375,
                    height: 667
                ),
                scale: 2,
                topFeature: IPhoneTopFeatureInfo(
                    kind: .none,
                    geometryAvailable: false,
                    curveAvailable: false,
                    size: nil,
                    paddingTop: nil
                )
            )
        case .iPhone12Mini:
            return IPhoneScreenInfo(
                cornerRadiusPoints: 44,
                dpi: 476,
                pixels: CGSize(
                    width: 1080,
                    height: 2340
                ),
                points: CGSize(
                    width: 360,
                    height: 780
                ),
                scale: 3,
                topFeature: IPhoneTopFeatureInfo(
                    kind: .notch,
                    geometryAvailable: true,
                    curveAvailable: true,
                    size: CGSize(
                        width: 242,
                        height: 34
                    ),
                    paddingTop: 0
                )
            )
        case .iPhone12:
            return IPhoneScreenInfo(
                cornerRadiusPoints: 47,
                dpi: 460,
                pixels: CGSize(
                    width: 1170,
                    height: 2532
                ),
                points: CGSize(
                    width: 390,
                    height: 844
                ),
                scale: 3,
                topFeature: IPhoneTopFeatureInfo(
                    kind: .notch,
                    geometryAvailable: true,
                    curveAvailable: true,
                    size: CGSize(
                        width: 222,
                        height: 32
                    ),
                    paddingTop: 0
                )
            )
        case .iPhone12Pro:
            return IPhoneScreenInfo(
                cornerRadiusPoints: 47,
                dpi: 460,
                pixels: CGSize(
                    width: 1170,
                    height: 2532
                ),
                points: CGSize(
                    width: 390,
                    height: 844
                ),
                scale: 3,
                topFeature: IPhoneTopFeatureInfo(
                    kind: .notch,
                    geometryAvailable: true,
                    curveAvailable: true,
                    size: CGSize(
                        width: 222,
                        height: 32
                    ),
                    paddingTop: 0
                )
            )
        case .iPhone12ProMax:
            return IPhoneScreenInfo(
                cornerRadiusPoints: 53,
                dpi: 458,
                pixels: CGSize(
                    width: 1284,
                    height: 2778
                ),
                points: CGSize(
                    width: 428,
                    height: 926
                ),
                scale: 3,
                topFeature: IPhoneTopFeatureInfo(
                    kind: .notch,
                    geometryAvailable: true,
                    curveAvailable: true,
                    size: CGSize(
                        width: 222,
                        height: 32
                    ),
                    paddingTop: 0
                )
            )
        case .iPhone13Pro:
            return IPhoneScreenInfo(
                cornerRadiusPoints: 47.33333206176758,
                dpi: 460,
                pixels: CGSize(
                    width: 1170,
                    height: 2532
                ),
                points: CGSize(
                    width: 390,
                    height: 844
                ),
                scale: 3,
                topFeature: IPhoneTopFeatureInfo(
                    kind: .notch,
                    geometryAvailable: true,
                    curveAvailable: true,
                    size: CGSize(
                        width: 176,
                        height: 34
                    ),
                    paddingTop: 0
                )
            )
        case .iPhone13ProMax:
            return IPhoneScreenInfo(
                cornerRadiusPoints: 53.33333206176758,
                dpi: 458,
                pixels: CGSize(
                    width: 1284,
                    height: 2778
                ),
                points: CGSize(
                    width: 428,
                    height: 926
                ),
                scale: 3,
                topFeature: IPhoneTopFeatureInfo(
                    kind: .notch,
                    geometryAvailable: true,
                    curveAvailable: true,
                    size: CGSize(
                        width: 174,
                        height: 34
                    ),
                    paddingTop: 0
                )
            )
        case .iPhone13Mini:
            return IPhoneScreenInfo(
                cornerRadiusPoints: 44,
                dpi: 476,
                pixels: CGSize(
                    width: 1080,
                    height: 2340
                ),
                points: CGSize(
                    width: 360,
                    height: 780
                ),
                scale: 3,
                topFeature: IPhoneTopFeatureInfo(
                    kind: .notch,
                    geometryAvailable: true,
                    curveAvailable: true,
                    size: CGSize(
                        width: 189,
                        height: 38
                    ),
                    paddingTop: 0
                )
            )
        case .iPhone13:
            return IPhoneScreenInfo(
                cornerRadiusPoints: 47.33333206176758,
                dpi: 460,
                pixels: CGSize(
                    width: 1170,
                    height: 2532
                ),
                points: CGSize(
                    width: 390,
                    height: 844
                ),
                scale: 3,
                topFeature: IPhoneTopFeatureInfo(
                    kind: .notch,
                    geometryAvailable: true,
                    curveAvailable: true,
                    size: CGSize(
                        width: 176,
                        height: 34
                    ),
                    paddingTop: 0
                )
            )
        case .iPhoneSE3rdGeneration:
            return IPhoneScreenInfo(
                cornerRadiusPoints: 0,
                dpi: 326,
                pixels: CGSize(
                    width: 750,
                    height: 1334
                ),
                points: CGSize(
                    width: 375,
                    height: 667
                ),
                scale: 2,
                topFeature: IPhoneTopFeatureInfo(
                    kind: .none,
                    geometryAvailable: false,
                    curveAvailable: false,
                    size: nil,
                    paddingTop: nil
                )
            )
        case .iPhone14:
            return IPhoneScreenInfo(
                cornerRadiusPoints: 47.33333206176758,
                dpi: 460,
                pixels: CGSize(
                    width: 1170,
                    height: 2532
                ),
                points: CGSize(
                    width: 390,
                    height: 844
                ),
                scale: 3,
                topFeature: IPhoneTopFeatureInfo(
                    kind: .notch,
                    geometryAvailable: true,
                    curveAvailable: true,
                    size: CGSize(
                        width: 176,
                        height: 34
                    ),
                    paddingTop: 0
                )
            )
        case .iPhone14Plus:
            return IPhoneScreenInfo(
                cornerRadiusPoints: 53.33333206176758,
                dpi: 458,
                pixels: CGSize(
                    width: 1284,
                    height: 2778
                ),
                points: CGSize(
                    width: 428,
                    height: 926
                ),
                scale: 3,
                topFeature: IPhoneTopFeatureInfo(
                    kind: .notch,
                    geometryAvailable: true,
                    curveAvailable: true,
                    size: CGSize(
                        width: 174,
                        height: 34
                    ),
                    paddingTop: 0
                )
            )
        case .iPhone14Pro:
            return IPhoneScreenInfo(
                cornerRadiusPoints: 55,
                dpi: 460,
                pixels: CGSize(
                    width: 1179,
                    height: 2556
                ),
                points: CGSize(
                    width: 393,
                    height: 852
                ),
                scale: 3,
                topFeature: IPhoneTopFeatureInfo(
                    kind: .dynamicIsland,
                    geometryAvailable: true,
                    curveAvailable: false,
                    size: CGSize(
                        width: 125,
                        height: 36.6667
                    ),
                    paddingTop: 11.3333
                )
            )
        case .iPhone14ProMax:
            return IPhoneScreenInfo(
                cornerRadiusPoints: 55,
                dpi: 460,
                pixels: CGSize(
                    width: 1290,
                    height: 2796
                ),
                points: CGSize(
                    width: 430,
                    height: 932
                ),
                scale: 3,
                topFeature: IPhoneTopFeatureInfo(
                    kind: .dynamicIsland,
                    geometryAvailable: true,
                    curveAvailable: false,
                    size: CGSize(
                        width: 125.3333,
                        height: 36.6667
                    ),
                    paddingTop: 11.3333
                )
            )
        case .iPhone15:
            return IPhoneScreenInfo(
                cornerRadiusPoints: 55,
                dpi: 460,
                pixels: CGSize(
                    width: 1179,
                    height: 2556
                ),
                points: CGSize(
                    width: 393,
                    height: 852
                ),
                scale: 3,
                topFeature: IPhoneTopFeatureInfo(
                    kind: .dynamicIsland,
                    geometryAvailable: true,
                    curveAvailable: false,
                    size: CGSize(
                        width: 125,
                        height: 36.6667
                    ),
                    paddingTop: 11.3333
                )
            )
        case .iPhone15Plus:
            return IPhoneScreenInfo(
                cornerRadiusPoints: 55,
                dpi: 460,
                pixels: CGSize(
                    width: 1290,
                    height: 2796
                ),
                points: CGSize(
                    width: 430,
                    height: 932
                ),
                scale: 3,
                topFeature: IPhoneTopFeatureInfo(
                    kind: .dynamicIsland,
                    geometryAvailable: true,
                    curveAvailable: false,
                    size: CGSize(
                        width: 125.3333,
                        height: 36.6667
                    ),
                    paddingTop: 11.3333
                )
            )
        case .iPhone15Pro:
            return IPhoneScreenInfo(
                cornerRadiusPoints: 55,
                dpi: 460,
                pixels: CGSize(
                    width: 1179,
                    height: 2556
                ),
                points: CGSize(
                    width: 393,
                    height: 852
                ),
                scale: 3,
                topFeature: IPhoneTopFeatureInfo(
                    kind: .dynamicIsland,
                    geometryAvailable: true,
                    curveAvailable: false,
                    size: CGSize(
                        width: 125,
                        height: 36.6667
                    ),
                    paddingTop: 11.3333
                )
            )
        case .iPhone15ProMax:
            return IPhoneScreenInfo(
                cornerRadiusPoints: 55,
                dpi: 460,
                pixels: CGSize(
                    width: 1290,
                    height: 2796
                ),
                points: CGSize(
                    width: 430,
                    height: 932
                ),
                scale: 3,
                topFeature: IPhoneTopFeatureInfo(
                    kind: .dynamicIsland,
                    geometryAvailable: true,
                    curveAvailable: false,
                    size: CGSize(
                        width: 125.3333,
                        height: 36.6667
                    ),
                    paddingTop: 11.3333
                )
            )
        case .iPhone16Pro:
            return IPhoneScreenInfo(
                cornerRadiusPoints: 62,
                dpi: 460,
                pixels: CGSize(
                    width: 1206,
                    height: 2622
                ),
                points: CGSize(
                    width: 402,
                    height: 874
                ),
                scale: 3,
                topFeature: IPhoneTopFeatureInfo(
                    kind: .dynamicIsland,
                    geometryAvailable: true,
                    curveAvailable: false,
                    size: CGSize(
                        width: 125,
                        height: 36.6667
                    ),
                    paddingTop: 14
                )
            )
        case .iPhone16ProMax:
            return IPhoneScreenInfo(
                cornerRadiusPoints: 62,
                dpi: 460,
                pixels: CGSize(
                    width: 1320,
                    height: 2868
                ),
                points: CGSize(
                    width: 440,
                    height: 956
                ),
                scale: 3,
                topFeature: IPhoneTopFeatureInfo(
                    kind: .dynamicIsland,
                    geometryAvailable: true,
                    curveAvailable: false,
                    size: CGSize(
                        width: 125.3333,
                        height: 36.6667
                    ),
                    paddingTop: 14
                )
            )
        case .iPhone16:
            return IPhoneScreenInfo(
                cornerRadiusPoints: 55,
                dpi: 460,
                pixels: CGSize(
                    width: 1179,
                    height: 2556
                ),
                points: CGSize(
                    width: 393,
                    height: 852
                ),
                scale: 3,
                topFeature: IPhoneTopFeatureInfo(
                    kind: .dynamicIsland,
                    geometryAvailable: true,
                    curveAvailable: false,
                    size: CGSize(
                        width: 125,
                        height: 36.6667
                    ),
                    paddingTop: 11.3333
                )
            )
        case .iPhone16Plus:
            return IPhoneScreenInfo(
                cornerRadiusPoints: 55,
                dpi: 460,
                pixels: CGSize(
                    width: 1290,
                    height: 2796
                ),
                points: CGSize(
                    width: 430,
                    height: 932
                ),
                scale: 3,
                topFeature: IPhoneTopFeatureInfo(
                    kind: .dynamicIsland,
                    geometryAvailable: true,
                    curveAvailable: false,
                    size: CGSize(
                        width: 125.3333,
                        height: 36.6667
                    ),
                    paddingTop: 11.3333
                )
            )
        case .iPhone16e:
            return IPhoneScreenInfo(
                cornerRadiusPoints: 47.33333206176758,
                dpi: 460,
                pixels: CGSize(
                    width: 1170,
                    height: 2532
                ),
                points: CGSize(
                    width: 390,
                    height: 844
                ),
                scale: 3,
                topFeature: IPhoneTopFeatureInfo(
                    kind: .notch,
                    geometryAvailable: true,
                    curveAvailable: true,
                    size: CGSize(
                        width: 176,
                        height: 34
                    ),
                    paddingTop: 0
                )
            )
        case .iPhone17Pro:
            return IPhoneScreenInfo(
                cornerRadiusPoints: 62,
                dpi: 460,
                pixels: CGSize(
                    width: 1206,
                    height: 2622
                ),
                points: CGSize(
                    width: 402,
                    height: 874
                ),
                scale: 3,
                topFeature: IPhoneTopFeatureInfo(
                    kind: .dynamicIsland,
                    geometryAvailable: true,
                    curveAvailable: false,
                    size: CGSize(
                        width: 125,
                        height: 36.6667
                    ),
                    paddingTop: 14
                )
            )
        case .iPhone17ProMax:
            return IPhoneScreenInfo(
                cornerRadiusPoints: 62,
                dpi: 460,
                pixels: CGSize(
                    width: 1320,
                    height: 2868
                ),
                points: CGSize(
                    width: 440,
                    height: 956
                ),
                scale: 3,
                topFeature: IPhoneTopFeatureInfo(
                    kind: .dynamicIsland,
                    geometryAvailable: true,
                    curveAvailable: false,
                    size: CGSize(
                        width: 125.3333,
                        height: 36.6667
                    ),
                    paddingTop: 14
                )
            )
        case .iPhone17:
            return IPhoneScreenInfo(
                cornerRadiusPoints: 62,
                dpi: 460,
                pixels: CGSize(
                    width: 1206,
                    height: 2622
                ),
                points: CGSize(
                    width: 402,
                    height: 874
                ),
                scale: 3,
                topFeature: IPhoneTopFeatureInfo(
                    kind: .dynamicIsland,
                    geometryAvailable: true,
                    curveAvailable: false,
                    size: CGSize(
                        width: 125,
                        height: 36.6667
                    ),
                    paddingTop: 14
                )
            )
        case .iPhoneAir:
            return IPhoneScreenInfo(
                cornerRadiusPoints: 62,
                dpi: 460,
                pixels: CGSize(
                    width: 1260,
                    height: 2736
                ),
                points: CGSize(
                    width: 420,
                    height: 912
                ),
                scale: 3,
                topFeature: IPhoneTopFeatureInfo(
                    kind: .dynamicIsland,
                    geometryAvailable: true,
                    curveAvailable: false,
                    size: CGSize(
                        width: 125.3333,
                        height: 36.6667
                    ),
                    paddingTop: 20
                )
            )
        case .iPhone17e:
            return IPhoneScreenInfo(
                cornerRadiusPoints: 47.33333206176758,
                dpi: 460,
                pixels: CGSize(
                    width: 1170,
                    height: 2532
                ),
                points: CGSize(
                    width: 390,
                    height: 844
                ),
                scale: 3,
                topFeature: IPhoneTopFeatureInfo(
                    kind: .notch,
                    geometryAvailable: true,
                    curveAvailable: true,
                    size: CGSize(
                        width: 176,
                        height: 34
                    ),
                    paddingTop: 0
                )
            )
        }
    }
}
