import UIKit

// Generated by inspect_simulator_topcutouts.py
extension IPhoneDevice {
    public var topFeature: IPhoneTopFeatureInfo {
        switch self {
        case .iPhone6s:
            return IPhoneTopFeatureInfo(
                kind: .none,
                geometryAvailable: false,
                curveAvailable: false,
                size: nil,
                paddingTop: nil
            )
        case .iPhone6sPlus:
            return IPhoneTopFeatureInfo(
                kind: .none,
                geometryAvailable: false,
                curveAvailable: false,
                size: nil,
                paddingTop: nil
            )
        case .iPhoneSE1stGeneration:
            return IPhoneTopFeatureInfo(
                kind: .none,
                geometryAvailable: false,
                curveAvailable: false,
                size: nil,
                paddingTop: nil
            )
        case .iPhone7:
            return IPhoneTopFeatureInfo(
                kind: .none,
                geometryAvailable: false,
                curveAvailable: false,
                size: nil,
                paddingTop: nil
            )
        case .iPhone7Plus:
            return IPhoneTopFeatureInfo(
                kind: .none,
                geometryAvailable: false,
                curveAvailable: false,
                size: nil,
                paddingTop: nil
            )
        case .iPhone8:
            return IPhoneTopFeatureInfo(
                kind: .none,
                geometryAvailable: false,
                curveAvailable: false,
                size: nil,
                paddingTop: nil
            )
        case .iPhone8Plus:
            return IPhoneTopFeatureInfo(
                kind: .none,
                geometryAvailable: false,
                curveAvailable: false,
                size: nil,
                paddingTop: nil
            )
        case .iPhoneX:
            return IPhoneTopFeatureInfo(
                kind: .notch,
                geometryAvailable: true,
                curveAvailable: true,
                size: CGSize(
                    width: 223,
                    height: 30
                ),
                paddingTop: 0
            )
        case .iPhoneXs:
            return IPhoneTopFeatureInfo(
                kind: .notch,
                geometryAvailable: true,
                curveAvailable: true,
                size: CGSize(
                    width: 223,
                    height: 30
                ),
                paddingTop: 0
            )
        case .iPhoneXsMax:
            return IPhoneTopFeatureInfo(
                kind: .notch,
                geometryAvailable: true,
                curveAvailable: true,
                size: CGSize(
                    width: 223,
                    height: 30
                ),
                paddingTop: 0
            )
        case .iPhoneXR:
            return IPhoneTopFeatureInfo(
                kind: .notch,
                geometryAvailable: true,
                curveAvailable: true,
                size: CGSize(
                    width: 245,
                    height: 33
                ),
                paddingTop: 0
            )
        case .iPhone11:
            return IPhoneTopFeatureInfo(
                kind: .notch,
                geometryAvailable: true,
                curveAvailable: true,
                size: CGSize(
                    width: 245,
                    height: 33
                ),
                paddingTop: 0
            )
        case .iPhone11Pro:
            return IPhoneTopFeatureInfo(
                kind: .notch,
                geometryAvailable: true,
                curveAvailable: true,
                size: CGSize(
                    width: 223,
                    height: 30
                ),
                paddingTop: 0
            )
        case .iPhone11ProMax:
            return IPhoneTopFeatureInfo(
                kind: .notch,
                geometryAvailable: true,
                curveAvailable: true,
                size: CGSize(
                    width: 223,
                    height: 30
                ),
                paddingTop: 0
            )
        case .iPhoneSE2ndGeneration:
            return IPhoneTopFeatureInfo(
                kind: .none,
                geometryAvailable: false,
                curveAvailable: false,
                size: nil,
                paddingTop: nil
            )
        case .iPhone12Mini:
            return IPhoneTopFeatureInfo(
                kind: .notch,
                geometryAvailable: true,
                curveAvailable: true,
                size: CGSize(
                    width: 242,
                    height: 34
                ),
                paddingTop: 0
            )
        case .iPhone12:
            return IPhoneTopFeatureInfo(
                kind: .notch,
                geometryAvailable: true,
                curveAvailable: true,
                size: CGSize(
                    width: 222,
                    height: 32
                ),
                paddingTop: 0
            )
        case .iPhone12Pro:
            return IPhoneTopFeatureInfo(
                kind: .notch,
                geometryAvailable: true,
                curveAvailable: true,
                size: CGSize(
                    width: 222,
                    height: 32
                ),
                paddingTop: 0
            )
        case .iPhone12ProMax:
            return IPhoneTopFeatureInfo(
                kind: .notch,
                geometryAvailable: true,
                curveAvailable: true,
                size: CGSize(
                    width: 222,
                    height: 32
                ),
                paddingTop: 0
            )
        case .iPhone13Pro:
            return IPhoneTopFeatureInfo(
                kind: .notch,
                geometryAvailable: true,
                curveAvailable: true,
                size: CGSize(
                    width: 176,
                    height: 34
                ),
                paddingTop: 0
            )
        case .iPhone13ProMax:
            return IPhoneTopFeatureInfo(
                kind: .notch,
                geometryAvailable: true,
                curveAvailable: true,
                size: CGSize(
                    width: 174,
                    height: 34
                ),
                paddingTop: 0
            )
        case .iPhone13Mini:
            return IPhoneTopFeatureInfo(
                kind: .notch,
                geometryAvailable: true,
                curveAvailable: true,
                size: CGSize(
                    width: 189,
                    height: 38
                ),
                paddingTop: 0
            )
        case .iPhone13:
            return IPhoneTopFeatureInfo(
                kind: .notch,
                geometryAvailable: true,
                curveAvailable: true,
                size: CGSize(
                    width: 176,
                    height: 34
                ),
                paddingTop: 0
            )
        case .iPhoneSE3rdGeneration:
            return IPhoneTopFeatureInfo(
                kind: .none,
                geometryAvailable: false,
                curveAvailable: false,
                size: nil,
                paddingTop: nil
            )
        case .iPhone14:
            return IPhoneTopFeatureInfo(
                kind: .notch,
                geometryAvailable: true,
                curveAvailable: true,
                size: CGSize(
                    width: 176,
                    height: 34
                ),
                paddingTop: 0
            )
        case .iPhone14Plus:
            return IPhoneTopFeatureInfo(
                kind: .notch,
                geometryAvailable: true,
                curveAvailable: true,
                size: CGSize(
                    width: 174,
                    height: 34
                ),
                paddingTop: 0
            )
        case .iPhone14Pro:
            return IPhoneTopFeatureInfo(
                kind: .dynamicIsland,
                geometryAvailable: true,
                curveAvailable: false,
                size: CGSize(
                    width: 125,
                    height: 36.6667
                ),
                paddingTop: 11.3333
            )
        case .iPhone14ProMax:
            return IPhoneTopFeatureInfo(
                kind: .dynamicIsland,
                geometryAvailable: true,
                curveAvailable: false,
                size: CGSize(
                    width: 125.3333,
                    height: 36.6667
                ),
                paddingTop: 11.3333
            )
        case .iPhone15:
            return IPhoneTopFeatureInfo(
                kind: .dynamicIsland,
                geometryAvailable: true,
                curveAvailable: false,
                size: CGSize(
                    width: 125,
                    height: 36.6667
                ),
                paddingTop: 11.3333
            )
        case .iPhone15Plus:
            return IPhoneTopFeatureInfo(
                kind: .dynamicIsland,
                geometryAvailable: true,
                curveAvailable: false,
                size: CGSize(
                    width: 125.3333,
                    height: 36.6667
                ),
                paddingTop: 11.3333
            )
        case .iPhone15Pro:
            return IPhoneTopFeatureInfo(
                kind: .dynamicIsland,
                geometryAvailable: true,
                curveAvailable: false,
                size: CGSize(
                    width: 125,
                    height: 36.6667
                ),
                paddingTop: 11.3333
            )
        case .iPhone15ProMax:
            return IPhoneTopFeatureInfo(
                kind: .dynamicIsland,
                geometryAvailable: true,
                curveAvailable: false,
                size: CGSize(
                    width: 125.3333,
                    height: 36.6667
                ),
                paddingTop: 11.3333
            )
        case .iPhone16Pro:
            return IPhoneTopFeatureInfo(
                kind: .dynamicIsland,
                geometryAvailable: true,
                curveAvailable: false,
                size: CGSize(
                    width: 125,
                    height: 36.6667
                ),
                paddingTop: 14
            )
        case .iPhone16ProMax:
            return IPhoneTopFeatureInfo(
                kind: .dynamicIsland,
                geometryAvailable: true,
                curveAvailable: false,
                size: CGSize(
                    width: 125.3333,
                    height: 36.6667
                ),
                paddingTop: 14
            )
        case .iPhone16:
            return IPhoneTopFeatureInfo(
                kind: .dynamicIsland,
                geometryAvailable: true,
                curveAvailable: false,
                size: CGSize(
                    width: 125,
                    height: 36.6667
                ),
                paddingTop: 11.3333
            )
        case .iPhone16Plus:
            return IPhoneTopFeatureInfo(
                kind: .dynamicIsland,
                geometryAvailable: true,
                curveAvailable: false,
                size: CGSize(
                    width: 125.3333,
                    height: 36.6667
                ),
                paddingTop: 11.3333
            )
        case .iPhone16e:
            return IPhoneTopFeatureInfo(
                kind: .notch,
                geometryAvailable: true,
                curveAvailable: true,
                size: CGSize(
                    width: 176,
                    height: 34
                ),
                paddingTop: 0
            )
        case .iPhone17Pro:
            return IPhoneTopFeatureInfo(
                kind: .dynamicIsland,
                geometryAvailable: true,
                curveAvailable: false,
                size: CGSize(
                    width: 125,
                    height: 36.6667
                ),
                paddingTop: 14
            )
        case .iPhone17ProMax:
            return IPhoneTopFeatureInfo(
                kind: .dynamicIsland,
                geometryAvailable: true,
                curveAvailable: false,
                size: CGSize(
                    width: 125.3333,
                    height: 36.6667
                ),
                paddingTop: 14
            )
        case .iPhone17:
            return IPhoneTopFeatureInfo(
                kind: .dynamicIsland,
                geometryAvailable: true,
                curveAvailable: false,
                size: CGSize(
                    width: 125,
                    height: 36.6667
                ),
                paddingTop: 14
            )
        case .iPhoneAir:
            return IPhoneTopFeatureInfo(
                kind: .dynamicIsland,
                geometryAvailable: true,
                curveAvailable: false,
                size: CGSize(
                    width: 125.3333,
                    height: 36.6667
                ),
                paddingTop: 20
            )
        case .iPhone17e:
            return IPhoneTopFeatureInfo(
                kind: .notch,
                geometryAvailable: true,
                curveAvailable: true,
                size: CGSize(
                    width: 176,
                    height: 34
                ),
                paddingTop: 0
            )
        }
    }
}
