import UIKit

// This file is generated by generate_top_cutout_catalog.swift.
// Do not edit it directly. Update top_cutout_catalog.json and regenerate instead.

extension IPhoneTopCutoutCatalog {
    static func generatedHeuristicGeometry(
        screenSize: CGSize,
        safeAreaTop: CGFloat
    ) -> TopCutoutGeometry? {
        let width = Int(screenSize.width.rounded())
        let top = Int(safeAreaTop.rounded())

        switch (width, top) {
        case (375, 44):
            return wideNotch375
        case (414, 44):
            return wideNotch414
        case (390, 47):
            return narrowNotch390
        case (428, 47):
            return narrowNotch428
        case (428, 53):
            return narrowNotch428
        case (375, 50):
            return narrowNotch375MiniEstimate
        case (393, 59):
            return dynamicIsland393
        case (430, 59):
            return dynamicIsland430
        case (402, 62):
            return dynamicIsland402
        case (440, 62):
            return dynamicIsland440
        case (420, 68):
            return dynamicIsland420
        default:
            return nil
        }
    }

    static let wideNotch375 = TopCutoutGeometry(
        style: .wideNotch,
        size: CGSize(width: 209, height: 30),
        topInset: 0
    )

    static let wideNotch414 = TopCutoutGeometry(
        style: .wideNotch,
        size: CGSize(width: 210, height: 30),
        topInset: 0
    )

    static let wideNotch390 = TopCutoutGeometry(
        style: .wideNotch,
        size: CGSize(width: 210, height: 32),
        topInset: 0
    )

    static let wideNotch375Mini = TopCutoutGeometry(
        style: .wideNotch,
        size: CGSize(width: 227, height: 34),
        topInset: 0
    )

    static let narrowNotch390 = TopCutoutGeometry(
        style: .narrowNotch,
        size: CGSize(width: 162, height: 33),
        topInset: 0
    )

    static let narrowNotch428 = TopCutoutGeometry(
        style: .narrowNotch,
        size: CGSize(width: 162, height: 33),
        topInset: 0
    )

    static let narrowNotch375MiniEstimate = TopCutoutGeometry(
        style: .narrowNotch,
        size: CGSize(width: 168, height: 34),
        topInset: 0
    )

    static let dynamicIsland393 = TopCutoutGeometry(
        style: .dynamicIsland,
        size: CGSize(width: 125, height: 37),
        topInset: 11
    )

    static let dynamicIsland430 = TopCutoutGeometry(
        style: .dynamicIsland,
        size: CGSize(width: 125, height: 37),
        topInset: 11
    )

    static let dynamicIsland402 = TopCutoutGeometry(
        style: .dynamicIsland,
        size: CGSize(width: 125, height: 37),
        topInset: 14
    )

    static let dynamicIsland440 = TopCutoutGeometry(
        style: .dynamicIsland,
        size: CGSize(width: 125, height: 37),
        topInset: 14
    )

    static let dynamicIsland420 = TopCutoutGeometry(
        style: .dynamicIsland,
        size: CGSize(width: 125, height: 37),
        topInset: 14
    )

    static let wideNotch390Max = TopCutoutGeometry(
        style: .wideNotch,
        size: CGSize(width: 210, height: 32),
        topInset: 0
    )

    static let generatedMap: [String: TopCutoutGeometry] = {
        var result: [String: TopCutoutGeometry] = [:]

        func assign(_ ids: [String], _ geometry: TopCutoutGeometry) {
            ids.forEach { result[$0] = geometry }
        }

        // iPhone X / XS / 11 Pro
        assign([
            "iPhone10,3", // iPhone X
            "iPhone10,6", // iPhone X
            "iPhone11,2", // iPhone XS
            "iPhone12,3", // iPhone 11 Pro
        ], wideNotch375)

        // iPhone XR / XS Max / 11 / 11 Pro Max
        assign([
            "iPhone11,8", // iPhone XR
            "iPhone11,4", // iPhone XS Max
            "iPhone11,6", // iPhone XS Max
            "iPhone12,1", // iPhone 11
            "iPhone12,5", // iPhone 11 Pro Max
        ], wideNotch414)

        // iPhone 12 / 12 Pro
        assign([
            "iPhone13,2", // iPhone 12
            "iPhone13,3", // iPhone 12 Pro
        ], wideNotch390)

        // iPhone 12 Pro Max
        assign([
            "iPhone13,4"
        ], wideNotch390Max)

        // iPhone 12 mini
        assign([
            "iPhone13,1"
        ], wideNotch375Mini)

        // iPhone 13 / 13 Pro / 14 / 16e / 17e
        assign([
            "iPhone14,5", // iPhone 13
            "iPhone14,2", // iPhone 13 Pro
            "iPhone14,7", // iPhone 14
            "iPhone17,5", // iPhone 16e
            "iPhone18,5", // iPhone 17e
        ], narrowNotch390)

        // iPhone 13 Pro Max / 14 Plus
        assign([
            "iPhone14,3", // iPhone 13 Pro Max
            "iPhone14,8", // iPhone 14 Plus
        ], narrowNotch428)

        // iPhone 13 mini
        assign([
            "iPhone14,4"
        ], narrowNotch375MiniEstimate)

        // iPhone 14 Pro / 15 / 15 Pro / 16
        assign([
            "iPhone15,2", // iPhone 14 Pro
            "iPhone15,4", // iPhone 15
            "iPhone16,1", // iPhone 15 Pro
            "iPhone17,3", // iPhone 16
        ], dynamicIsland393)

        // iPhone 14 Pro Max / 15 Plus / 15 Pro Max / 16 Plus
        assign([
            "iPhone15,3", // iPhone 14 Pro Max
            "iPhone15,5", // iPhone 15 Plus
            "iPhone16,2", // iPhone 15 Pro Max
            "iPhone17,4", // iPhone 16 Plus
        ], dynamicIsland430)

        // iPhone 16 Pro / 17 / 17 Pro
        assign([
            "iPhone17,1", // iPhone 16 Pro
            "iPhone18,3", // iPhone 17
            "iPhone18,1", // iPhone 17 Pro
        ], dynamicIsland402)

        // iPhone 16 Pro Max / 17 Pro Max
        assign([
            "iPhone17,2", // iPhone 16 Pro Max
            "iPhone18,2", // iPhone 17 Pro Max
        ], dynamicIsland440)

        // iPhone Air
        assign([
            "iPhone18,4"
        ], dynamicIsland420)

        return result
    }()
}
