// Generated by inspect_simulator_topcutouts.py
extension TopCutoutCatalog {
    /// A generated catalog of supported iPhone model identifiers.
    ///
    /// The enum raw value is the model identifier returned by the system, such as `"iPhone16,1"`.
    /// Each case exposes additional generated metadata through ``displayName``, ``screen``, and
    /// ``sensorHousingPath``.
    public enum Device: String, CaseIterable, Sendable {
        case iPhone6s = "iPhone8,1"
        case iPhone6sPlus = "iPhone8,2"
        case iPhoneSE1stGeneration = "iPhone8,4"
        case iPhone7 = "iPhone9,1"
        case iPhone7Plus = "iPhone9,2"
        case iPhone8 = "iPhone10,4"
        case iPhone8Plus = "iPhone10,5"
        case iPhoneX = "iPhone10,6"
        case iPhoneXs = "iPhone11,2"
        case iPhoneXsMax = "iPhone11,4"
        case iPhoneXR = "iPhone11,8"
        case iPhone11 = "iPhone12,1"
        case iPhone11Pro = "iPhone12,3"
        case iPhone11ProMax = "iPhone12,5"
        case iPhoneSE2ndGeneration = "iPhone12,8"
        case iPhone12Mini = "iPhone13,1"
        case iPhone12 = "iPhone13,2"
        case iPhone12Pro = "iPhone13,3"
        case iPhone12ProMax = "iPhone13,4"
        case iPhone13Pro = "iPhone14,2"
        case iPhone13ProMax = "iPhone14,3"
        case iPhone13Mini = "iPhone14,4"
        case iPhone13 = "iPhone14,5"
        case iPhoneSE3rdGeneration = "iPhone14,6"
        case iPhone14 = "iPhone14,7"
        case iPhone14Plus = "iPhone14,8"
        case iPhone14Pro = "iPhone15,2"
        case iPhone14ProMax = "iPhone15,3"
        case iPhone15 = "iPhone15,4"
        case iPhone15Plus = "iPhone15,5"
        case iPhone15Pro = "iPhone16,1"
        case iPhone15ProMax = "iPhone16,2"
        case iPhone16Pro = "iPhone17,1"
        case iPhone16ProMax = "iPhone17,2"
        case iPhone16 = "iPhone17,3"
        case iPhone16Plus = "iPhone17,4"
        case iPhone16e = "iPhone17,5"
        case iPhone17Pro = "iPhone18,1"
        case iPhone17ProMax = "iPhone18,2"
        case iPhone17 = "iPhone18,3"
        case iPhoneAir = "iPhone18,4"
        case iPhone17e = "iPhone18,5"
    }
}
