// Generated by inspect_simulator_topcutouts.py
extension TopCutoutCatalog.Device {
    /// A human-readable marketing name for the catalog entry.
    public var displayName: String {
        switch self {
        case .iPhone6s:
            return "iPhone 6s"
        case .iPhone6sPlus:
            return "iPhone 6s Plus"
        case .iPhoneSE1stGeneration:
            return "iPhone SE (1st generation)"
        case .iPhone7:
            return "iPhone 7"
        case .iPhone7Plus:
            return "iPhone 7 Plus"
        case .iPhone8:
            return "iPhone 8"
        case .iPhone8Plus:
            return "iPhone 8 Plus"
        case .iPhoneX:
            return "iPhone X"
        case .iPhoneXs:
            return "iPhone XS"
        case .iPhoneXsMax:
            return "iPhone XS Max"
        case .iPhoneXR:
            return "iPhone XR"
        case .iPhone11:
            return "iPhone 11"
        case .iPhone11Pro:
            return "iPhone 11 Pro"
        case .iPhone11ProMax:
            return "iPhone 11 Pro Max"
        case .iPhoneSE2ndGeneration:
            return "iPhone SE (2nd generation)"
        case .iPhone12Mini:
            return "iPhone 12 mini"
        case .iPhone12:
            return "iPhone 12"
        case .iPhone12Pro:
            return "iPhone 12 Pro"
        case .iPhone12ProMax:
            return "iPhone 12 Pro Max"
        case .iPhone13Pro:
            return "iPhone 13 Pro"
        case .iPhone13ProMax:
            return "iPhone 13 Pro Max"
        case .iPhone13Mini:
            return "iPhone 13 mini"
        case .iPhone13:
            return "iPhone 13"
        case .iPhoneSE3rdGeneration:
            return "iPhone SE (3rd generation)"
        case .iPhone14:
            return "iPhone 14"
        case .iPhone14Plus:
            return "iPhone 14 Plus"
        case .iPhone14Pro:
            return "iPhone 14 Pro"
        case .iPhone14ProMax:
            return "iPhone 14 Pro Max"
        case .iPhone15:
            return "iPhone 15"
        case .iPhone15Plus:
            return "iPhone 15 Plus"
        case .iPhone15Pro:
            return "iPhone 15 Pro"
        case .iPhone15ProMax:
            return "iPhone 15 Pro Max"
        case .iPhone16Pro:
            return "iPhone 16 Pro"
        case .iPhone16ProMax:
            return "iPhone 16 Pro Max"
        case .iPhone16:
            return "iPhone 16"
        case .iPhone16Plus:
            return "iPhone 16 Plus"
        case .iPhone16e:
            return "iPhone 16e"
        case .iPhone17Pro:
            return "iPhone 17 Pro"
        case .iPhone17ProMax:
            return "iPhone 17 Pro Max"
        case .iPhone17:
            return "iPhone 17"
        case .iPhoneAir:
            return "iPhone Air"
        case .iPhone17e:
            return "iPhone 17e"
        }
    }
}
